version: "2"
services:
  redbrick:
    image: 'redbrick/site:latest'
    container_name: 'redbrick-site'
    restart: 'always'
    volumes:
      - ./source:/usr/src/app/source
      - ./logs:/usr/src/app/logs
    ports:
      - '3000:3000'
    environment:
      SECRET_API_TOKEN: 'somethingThatMustChange'
      RECAPTCHA_SITE_KEY: ''
      RECAPTCHA_SECRET_KEY: ''
      LOG_ROTATE: '24h'
